import { Roboto } from 'next/font/google';
import '../globals.css';
import Header from '../components/Shared/Header/Header';
import Navbar from '../components/Shared/Navbar/Navbar';
import Footer from '../components/Shared/Footer/Footer';
import { Toaster } from 'sonner';
import NextAuthSessionProvider from '@/Providers/SessionProvider';
import RadixProvider from '@/Providers/RadixProvider';

const roboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap'
});

export const metadata = {
    title: 'LWSKart',
    description: 'Generated by LWSkart app'
};

export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'bn' }];
}

export default function LangLayout({ children, params }) {
    return (
        <html lang={params.lang}>
            <head>
        <meta name="cryptomus" content="713b3617" />
                <link rel='icon' href='/favicon.ico' />
            </head>
            <body className={roboto.className}>
                <NextAuthSessionProvider>
                    <RadixProvider>
                        <Header lang={params.lang} />
                        <Navbar lang={params.lang} />
                        {children}
                        <Footer lang={params.lang} />
                        <Toaster richColors />
                    </RadixProvider>
                </NextAuthSessionProvider>
            </body>
        </html>
    );
}
